kind: pipeline
name: default

steps:
- name: docker-push
  image: plugins/docker
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    PLUGIN_REPO: docker-registry.fruitice.fr/slack-cron
    PLUGIN_REGISTRY: docker-registry.fruitice.fr
    PLUGIN_TAG: ${DRONE_COMMIT}
  privileged: true
  when:
    branch: master
    event: push
    status: success